version: "3.8"
services:
  rag_api:
    build:
      context: .
      dockerfile: "./docker/rag_api/Dockerfile"
    image: rag_api
    container_name: rag_api
    volumes:
      - ./:/workspace
    ports:
      - 5001:5001
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - GSCHOLAR_TABLE=$GSCHOLAR_TABLE
      - OPENAI_API_KEY=$OPENAI_API_KEY
    depends_on:
      - pgvector

  pgvector:
    image: ankane/pgvector:v0.5.1
    container_name: pgvector
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - GSCHOLAR_TABLE=$GSCHOLAR_TABLE

  scraper:
    build:
      context: .
      dockerfile: "./docker/rag_api/Dockerfile"
    entrypoint: ["bash", "-c", "~/.pyenv/shims/python /workflow/scripts/gscholar_scraper.py"]
    image: rag_api
    container_name: scraper
    volumes:
      - ./scripts:/workflow/scripts
    environment:
      - RUN_SCRAPER=$RUN_SCRAPER
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - GSCHOLAR_TABLE=$GSCHOLAR_TABLE
    depends_on:
      - pgvector

  embed_gen:
    build:
      context: .
      dockerfile: "./docker/rag_api/Dockerfile"
    entrypoint: ["bash", "-c", "~/.pyenv/shims/python /workflow/scripts/generate_embeddings.py"]
    image: rag_api
    container_name: embed_gen
    volumes:
      - ./scripts:/workflow/scripts
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - RUN_EMBED_GEN=$RUN_EMBED_GEN
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - GSCHOLAR_TABLE=$GSCHOLAR_TABLE
    depends_on:
      - pgvector

networks:
  shared-network:
    external: false
